def updateConsulPin(environment, tenant, release_number) {
    echo 'updating pin in consul'
    sh(
        script: "ENVIRONMENT=${environment} PIN_ACTION=SET_PIN TENANT=${tenant} RELEASE_NUMBER=${release_number} scripts/consul-set-release-pin.sh ubuntu"
    )
}

def deleteConsulPin(environment, tenant) {
    echo 'deleting pin in consul'
    sh(
        script: "ENVIRONMENT=${environment} PIN_ACTION=DELETE_PIN TENANT=${tenant} scripts/consul-set-release-pin.sh ubuntu"
    )
}

def updateVersioningPin(environment, customer_id, release_number) {
    echo 'updating pin in versioning-manager'
    sh(
        script: "ENVIRONMENT=${environment} VERSIONING_ACTION=SET_CUSTOMER_PIN CUSTOMER_ID=${customer_id} RELEASE_NUMBER=${release_number} scripts/versioning-manager.sh ubuntu"
    )
}

def deleteVersioningPin(environment, customer_id) {
    echo 'deleting pin in versioning-manager'
    sh(
        script: "ENVIRONMENT=${environment} VERSIONING_ACTION=DELETE_CUSTOMER_PIN CUSTOMER_ID=${customer_id} scripts/versioning-manager.sh ubuntu"
    )
}

pipeline {
    agent any
    options {
        ansiColor('xterm')
        timestamps()
        buildDiscarder(logRotator(numToKeepStr: '10', artifactNumToKeepStr: '10'))
    }
    stages {
        stage ("setup") {
            steps {
                script {
                    // load utility function
                    def rootDir = pwd()
                    utils = load "${rootDir}/jenkins/groovy/Utils.groovy"
                    // checkout repos
                    utils.SetupRepos(env.VIDEO_INFRA_BRANCH)

                    // setup OCI credentials
                    utils.SetupOCI()
                }
            }
        }
        stage ("check that environment supports release backends") {
            steps {
                script {
                    dir("infra-provisioning") {
                        useReleaseBackends = utils.GetEnvironmentVar(env.ENVIRONMENT, "USE_RELEASE_BACKENDS")
                        echo useReleaseBackends
                        if (useReleaseBackends != 'true') {
                            error 'environment does not support tenant pinning'
                        }
                    }
                }
            }
        }
        stage ("check if versionining-manager is used for tenant release pins in this environment") {
            steps {
                script{ 
                    dir("infra-provisioning") {
                        versioningManagerURL = utils.GetEnvironmentVar(env.ENVIRONMENT, "VERSIONING_URL")
                        if (versioningManagerURL != 'false') {
                            versioningManagerDeployed = 'true'
                        }
                        echo 'versioning manager URL: ' + versioningManagerURL
                        echo 'versioning manager deployed: ' + versioningManagerDeployed
                    }
                }
            }
        }
        stage ("modify tenant release pin in consul") {
            when {
                allOf {
                    expression { useReleaseBackends == 'true' }
                    expression { versioningManagerDeployed != 'true' }
                }
            }
            steps {
                script {
                    echo "PIN_ACTION: ${env.PIN_ACTION}"
                    if (env.PIN_ACTION == 'SET_PIN') or (env.PIN_ACTION == 'SET_CUSTOMER_PIN') {
                        dir("infra-provisioning") {
                            withCredentials([
                                string(credentialsId: 'asap-jwt-kid-dev', variable: 'ASAP_JWT_KID_DEV'),
                                string(credentialsId: 'asap-jwt-kid-prod', variable: 'ASAP_JWT_KID_PROD'),
                                file(credentialsId: 'asap-jwt-key-dev', variable: 'ASAP_JWT_KEY_DEV'),
                                file(credentialsId: 'asap-jwt-key-prod', variable: 'ASAP_JWT_KEY_PROD')
                            ]) {
                                sshagent(credentials: ['ssh-ubuntu']) {
                                    updateConsulPin(env.ENVIRONMENT, env.TENANT, env.RELEASE_NUMBER)
                                }
                            }
                        }
                    } else if (env.PIN_ACTION == 'DELETE_PIN') {
                        dir("infra-provisioning") {
                            withCredentials([
                                string(credentialsId: 'asap-jwt-kid-dev', variable: 'ASAP_JWT_KID_DEV'),
                                string(credentialsId: 'asap-jwt-kid-prod', variable: 'ASAP_JWT_KID_PROD'),
                                file(credentialsId: 'asap-jwt-key-dev', variable: 'ASAP_JWT_KEY_DEV'),
                                file(credentialsId: 'asap-jwt-key-prod', variable: 'ASAP_JWT_KEY_PROD')
                            ]) {
                                sshagent(credentials: ['ssh-ubuntu']) {
                                    deleteConsulPin(env.ENVIRONMENT, env.TENANT)
                                }
                            }
                        }
                    } else {
                        error 'invalid PIN_ACTION; should be SET_PIN or DELETE_PIN'
                    }
                }
            }
        }
        stage ("modify customer pin in versioning-manager") {
            when {
                allOf {
                    expression { useReleaseBackends == 'true' }
                    expression { versioningManagerDeployed == 'true' }
                }
            }
            steps {
                script {
                    echo "PIN_ACTION: ${env.PIN_ACTION}"
                    if (env.PIN_ACTION == 'SET_PIN') {
                        dir("infra-provisioning") {
                            withCredentials([
                                string(credentialsId: 'asap-jwt-kid-dev', variable: 'ASAP_JWT_KID_DEV'),
                                string(credentialsId: 'asap-jwt-kid-prod', variable: 'ASAP_JWT_KID_PROD'),
                                file(credentialsId: 'asap-jwt-key-dev', variable: 'ASAP_JWT_KEY_DEV'),
                                file(credentialsId: 'asap-jwt-key-prod', variable: 'ASAP_JWT_KEY_PROD')
                            ]) {
                                sshagent(credentials: ['ssh-ubuntu']) {
                                    updateVersioningPin(env.ENVIRONMENT, env.CUSTOMER_ID, env.RELEASE_NUMBER)
                                }
                            }
                        }
                    } else if (env.PIN_ACTION == 'DELETE_PIN') {
                        dir("infra-provisioning") {
                            withCredentials([
                                string(credentialsId: 'asap-jwt-kid-dev', variable: 'ASAP_JWT_KID_DEV'),
                                string(credentialsId: 'asap-jwt-kid-prod', variable: 'ASAP_JWT_KID_PROD'),
                                file(credentialsId: 'asap-jwt-key-dev', variable: 'ASAP_JWT_KEY_DEV'),
                                file(credentialsId: 'asap-jwt-key-prod', variable: 'ASAP_JWT_KEY_PROD')
                            ]) {
                                sshagent(credentials: ['ssh-ubuntu']) {
                                    deleteVersioningPin(env.ENVIRONMENT, env.CUSTOMER_ID)
                                }
                            }
                        }
                    } else {
                        error 'invalid PIN_ACTION; should be SET_PIN or DELETE_PIN'
                    }
                }
            }
        }
    }
    post {
        always {
            cleanWs()  // clean up afterwards
        }
    }
}
