def utils
pipeline {
    agent any
    options {
        ansiColor('xterm')
        timestamps()
        buildDiscarder(logRotator(numToKeepStr: '10', artifactNumToKeepStr: '10'))
    }
    stages {
        // output stage, shows off our input parameters
        stage ("setup") {
            steps {
                script {
                    // load utility function
                    def rootDir = pwd()
                    utils = load "${rootDir}/jenkins/groovy/Utils.groovy"
                    // checkout repos
                    utils.SetupRepos(env.VIDEO_INFRA_BRANCH)

                    // setup OCI credentials
                    utils.SetupOCI()

                    sh 'mkdir -p test-results'
                }
            }
        }
        stage ("nomad pool provisioning") {
            steps {
                script {
                    echo 'nomad pool provision beginning'
                    dir('infra-provisioning') {
                        withCredentials([
                            string(credentialsId: 'oci-jenkins-terraform-aws-secret', variable: 'AWS_SECRET_ACCESS_KEY'),
                            string(credentialsId: 'oci-jenkins-terraform-aws-id', variable: 'AWS_ACCESS_KEY_ID'),
                            sshUserPrivateKey(credentialsId: 'ssh-ubuntu', keyFileVariable: 'USER_PRIVATE_KEY_PATH', usernameVariable: 'SSH_USERNAME')
                        ]) {
                            utils.SetupAnsible()
                            utils.SetupSSH()
                            sshagent (credentials: ['ssh-ubuntu']) {
                                sh '''#!/bin/bash
                                export USER_PUBLIC_KEY_PATH=~/.ssh/ssh_key.pub
                                export ORACLE_GIT_BRANCH=\"$RELEASE_BRANCH\"
                                terraform/nomad-gpu-pool/create-nomad-gpu-pool-stack.sh $SSH_USERNAME'''
                            }
                        }
                    }
                }
            }
        }
    }
}
