- job:
    name: configure-stick-table-entries
    display-name: configure stick table entries
    concurrent: true
    parameters:
      - infra-branch-param
      - string:
          name: ENVIRONMENT
          description: "Environment to find resources"
          trim: true
      - string:
          name: STICK_TABLE_ENTRIES
          description: 'JSON List of {{"key":"roomname","id":10}} to stick roomname to shard 0'
          trim: true
      - infra-repo-params

    project-type: pipeline
    sandbox: true
    pipeline-scm:
      scm:
        - infra-provisioning-checkout
      script-path: jenkins/groovy/configure-stick-table-entries/Jenkinsfile
      lightweight-checkout: true
