- job:
    name: configure-release-pin
    display-name: configure release pin
    description: 'Set or delete a pin from a customer to a specific release. Set may only be applied to the current or most recent GA release.'
    concurrent: true
    parameters:
      - string:
          name: CUSTOMER_ID
          default:
          description: "The customer ID, i.e., the URL directory for this customer's conferences. Do not include 'vpaas-magic-cookie-' at the beginning for JaaS."
          trim: true
      - string:
          name: PIN_ACTION
          default: "SET_PIN"
          description: "SET_PIN or DELETE_PIN"
          trim: true
      - string:
          name: RELEASE_NUMBER
          default:
          description: "The release number to pin to. This is the release job number. Only required for SET_PIN"
          trim: true
      - string:
          name: VIDEO_INFRA_BRANCH
          default: main
          description: "Controls checkout branch for infra repos, defaults to 'main'."
          trim: true
      - string:
          name: ENVIRONMENT
          default: lonely
          description: "Environment to build in, defaults to 'lonely'."
          trim: true
      - string:
          name: INFRA_CONFIGURATION_REPO
          default: git@github.com:jitsi/infra-configuration.git
          description: "Repo for configuration code (ansible etc), defaults to 'git@github.com:jitsi/infra-configuration.git'."
          trim: true
      - string:
          name: INFRA_CUSTOMIZATIONS_REPO
          default: git@github.com:jitsi/infra-customizations.git
          description: "Repo with customized configurations, defaults to 'git@github.com:jitsi/infra-customizations.git'."
          trim: true
 
    project-type: pipeline
    sandbox: true
    pipeline-scm:
      scm:
        - git:
            url: git@github.com:jitsi/infra-provisioning.git
            credentials-id: "video-infra"
            branches:
              - "origin/${VIDEO_INFRA_BRANCH}"
            browser: githubweb
            browser-url: https://github.com/jitsi/infra-provisioning
            submodule:
              recursive: true
      script-path: jenkins/groovy/configure-release-pin/Jenkinsfile
      lightweight-checkout: true
