- job:
    name: reconfigure-users-jenkins
    display-name: reconfigure users jenkins
    concurrent: false
    node: jenkins-local
    parameters:
      - infra-branch-param
      - infra-repo-params
    project-type: pipeline
    sandbox: true
    pipeline-scm:
      scm:
        - infra-provisioning-checkout
      script-path: jenkins/groovy/reconfigure-users-jenkins/Jenkinsfile
      lightweight-checkout: true
