- job:
    name: reconfigure-users-jenkins
    display-name: reconfigure users jenkins
    concurrent: false
    node: jenkins-local
    parameters:
      - string:
          name: VIDEO_INFRA_BRANCH
          default: main
          description: "Controls checkout branch for infra repos, defaults to 'main'."
          trim: true
      - string:
          name: INFRA_CONFIGURATION_REPO
          default: git@github.com:jitsi/infra-configuration.git
          description: "Repo for configuration code (ansible etc), defaults to 'git@github.com:jitsi/infra-configuration.git'."
          trim: true
      - string:
          name: INFRA_CUSTOMIZATIONS_REPO
          default: git@github.com:jitsi/infra-customizations.git
          description: "Repo with customized configurations, defaults to 'git@github.com:jitsi/infra-customizations.git'."
          trim: true
    project-type: pipeline
    sandbox: true
    pipeline-scm:
      scm:
        - git:
            url: git@github.com:jitsi/infra-provisioning.git
            credentials-id: "video-infra"
            branches:
              - "origin/${VIDEO_INFRA_BRANCH}"
            browser: githubweb
            browser-url: https://github.com/jitsi/infra-provisioning
            submodule:
              recursive: true
      script-path: jenkins/groovy/reconfigure-users-jenkins/Jenkinsfile
      lightweight-checkout: true
