pipeline {
    agent any
    options {
        timestamps()
        ansiColor('xterm')
    }
    stages {
        // output stage, shows off our input parameters
        stage ("build monitor-haproxy for beta-meet-jit-si") {
            steps {
                build(
                    job: 'monitor-haproxy',
                    parameters: [
                        string(
                            name: 'ENVIRONMENT',
                            value: 'beta-meet-jit-si',
                        ),
                        string(
                            name: 'VIDEO_INFRA_BRANCH',
                            value: "${env.VIDEO_INFRA_BRANCH}",
                        ),
                        string(
                            name: 'INFRA_CONFIGURATION_REPO',
                            value: "${env.INFRA_CONFIGURATION_REPO}",
                        ),
                        string(
                            name: 'INFRA_CUSTOMIZATIONS_REPO',
                            value: "${env.INFRA_CUSTOMIZATIONS_REPO}",
                        ),
                    ],
                )
            }
        }
    }
    post {
        always {
            cleanWs() // clean up
        }
    }
}
