def utils
pipeline {
    agent any
    options {
        ansiColor('xterm')
        timestamps()
        buildDiscarder(logRotator(numToKeepStr: '10', artifactNumToKeepStr: '10'))
    }
    stages {
        stage ("setup") {
            steps {
                script {
                    def rootDir = pwd()
                    utils = load "${rootDir}/jenkins/groovy/Utils.groovy"
                    utils.SetupRepos(env.VIDEO_INFRA_BRANCH)
                    utils.SetupOCI()
                    sh 'mkdir -p test-results'
                }
            }
        }
        stage ("nomad instance pool provisioning") {
            steps {
                script {
                    echo 'nomad instance pool provision beginning'
                    dir('infra-provisioning') {
                        withCredentials([
                            string(credentialsId: 'oci-jenkins-terraform-aws-secret', variable: 'AWS_SECRET_ACCESS_KEY'),
                            string(credentialsId: 'oci-jenkins-terraform-aws-id', variable: 'AWS_ACCESS_KEY_ID'),
                            sshUserPrivateKey(credentialsId: 'ssh-ubuntu', keyFileVariable: 'USER_PRIVATE_KEY_PATH', usernameVariable: 'SSH_USERNAME')
                        ]) {
                            utils.SetupAnsible()
                            utils.SetupSSH()

                            def pool_type = env.POOL_TYPE.toLowerCase()
                            def create_script = "create-nomad-${pool_type}-pool-stack.sh"

                            if (!fileExists("terraform/nomad-instance-pool/$create_script")) {
                                error("No known job type: ${env.JOB_TYPE}")
                            }

                            sshagent (credentials: ['ssh-ubuntu']) {
                                sh """#!/bin/bash
                                export USER_PUBLIC_KEY_PATH=~/.ssh/ssh_key.pub
                                export ORACLE_GIT_BRANCH=\"$RELEASE_BRANCH\"
                                terraform/nomad-instance-pool/${create_script} $SSH_USERNAME"""
                            }
                        }
                    }
                }
            }
        }
    }
}
