def utils
def torture_user
def torture_secret
pipeline {
    agent any
    options {
      ansiColor('xterm')
      timestamps()
      buildDiscarder(logRotator(daysToKeepStr: '14'))
    }
    stages {
        stage ("setup") {
            steps {
                script {
                    // load utility function
                    def rootDir = pwd()
                    utils = load "${rootDir}/jenkins/groovy/Utils.groovy"
                    // checkout repos
                    utils.SetupRepos(env.VIDEO_INFRA_BRANCH)
                }
            }
        }  
        stage ("load github credentials") {
            steps {
                script {
                    dir("infra-configuration") {
                        withCredentials([
                            string(credentialsId: 'ansible-vault-password', variable: 'ANSIBLE_VAULT_PASSWORD_PATH')
                        ]) {
                            utils.SetupAnsible()
                            torture_user = sh(
                                returnStdout: true,
                                script: """#!/bin/bash
                                LOCAL_PATH=\$(realpath \$(dirname "\${BASH_SOURCE[0]}"))
                                ENCRYPTED_CREDENTIALS_FILE="\$LOCAL_PATH/ansible/secrets/torture.yml"
                                echo \$(ansible-vault view \$ENCRYPTED_CREDENTIALS_FILE --vault-password .vault-password.txt | yq eval ".torture_github_user" -)"""
                            ).trim()
                            torture_secret = sh(
                                returnStdout: true,
                                script: """#!/bin/bash
                                LOCAL_PATH=\$(realpath \$(dirname "\${BASH_SOURCE[0]}"))
                                ENCRYPTED_CREDENTIALS_FILE="\$LOCAL_PATH/ansible/secrets/torture.yml"
                                echo \$(ansible-vault view \$ENCRYPTED_CREDENTIALS_FILE --vault-password .vault-password.txt | yq eval ".torture_github_token" -)"""
                            ).trim()
                        }
                    }
                }
            }
        }
        stage ("clone torture test repo") {
            steps {
                script {
                    dir('jitsi-meet-torture') {
                        try {
                            git branch: env.TORTURE_TEST_BRANCH, url: env.TORTURE_TEST_REPO, credentialsId: 'video-infra'
                        } catch (hudson.AbortException e) {
                            if (e.toString().contains('Couldn\'t find any revision to build')) {
                                echo "WARNING: couldn't find branch ${branch} in torture test repo, falling back to master"
                                git branch: 'master', url: env.TORTURE_TEST_REPO, credentialsId: 'video-infra'
                            }
                        }
                    }
                }
            }
        }
        stage ("run longlived conference test") {
            steps {
                script {
                    dir("infra-provisioning") {
                        withCredentials([
                            string(credentialsId: 'jenkins-aws-secret', variable: 'AWS_SECRET_ACCESS_KEY'),
                            string(credentialsId: 'jenkins-aws-id', variable: 'AWS_ACCESS_KEY_ID'),
                            string(credentialsId: 'asap-client-jwt-kid-meet', variable: 'ASAP_CLIENT_JWT_KID_MEET'),
                            string(credentialsId: 'asap-client-jwt-kid-beta', variable: 'ASAP_CLIENT_JWT_KID_BETA'),
                            string(credentialsId: 'asap-client-jwt-kid-prod', variable: 'ASAP_CLIENT_JWT_KID_PROD'),
                            string(credentialsId: 'asap-client-jwt-kid-stage', variable: 'ASAP_CLIENT_JWT_KID_STAGE'),
                            file(credentialsId: 'asap-client-jwt-key-meet', variable: 'ASAP_CLIENT_JWT_KEY_MEET'),
                            file(credentialsId: 'asap-client-jwt-key-prod', variable: 'ASAP_CLIENT_JWT_KEY_PROD'),
                            file(credentialsId: 'asap-client-jwt-key-stage', variable: 'ASAP_CLIENT_JWT_KEY_STAGE'),
                            file(credentialsId: 'asap-client-jwt-key-beta', variable: 'ASAP_CLIENT_JWT_KEY_BETA'),
                            sshUserPrivateKey(credentialsId: 'ssh-ubuntu', keyFileVariable: 'CONNECTION_SSH_PRIVATE_KEY_FILE', usernameVariable: 'SSH_USERNAME')
                        ]) {
                            sshagent (credentials: ['ssh-ubuntu']) {
                                sh(
                                    script: """#!/bin/bash
                                    set +x
                                    AWS_SECRET_ACCESS_KEY=${env.AWS_SECRET_ACCESS_KEY} \
                                    AWS_ACCESS_KEY_ID=${env.AWS_ACCESS_KEY_ID} \
                                    ASAP_CLIENT_JWT_KID_MEET=${env.ASAP_CLIENT_JWT_KID_MEET} \
                                    ASAP_CLIENT_JWT_KID_BETA=${env.ASAP_CLIENT_JWT_KID_BETA} \
                                    ASAP_CLIENT_JWT_KID_PROD=${env.ASAP_CLIENT_JWT_KID_PROD} \
                                    ASAP_CLIENT_JWT_KID_STAGE=${env.ASAP_CLIENT_JWT_KID_STAGE} \
                                    ASAP_CLIENT_JWT_KEY_MEET=${env.ASAP_CLIENT_JWT_KEY_MEET} \
                                    ASAP_CLIENT_JWT_KEY_PROD=${env.ASAP_CLIENT_JWT_KEY_PROD} \
                                    ASAP_CLIENT_JWT_KEY_STAGE=${env.ASAP_CLIENT_JWT_KEY_STAGE} \
                                    ASAP_CLIENT_JWT_KEY_BETA=${env.ASAP_CLIENT_JWT_KEY_BETA} \
                                    TORTURE_GITHUB_USER=${torture_user} TORTURE_GITHUB_TOKEN=${torture_secret} scripts/synthetic-longlived-test.sh"""
                                )
                            }
                        }
                    }
                }
            }
        }
    }
    post {
        always {
            junit 'jitsi-meet-torture/target/*/xml/*.xml'
            archiveArtifacts artifacts: 'jitsi-meet-torture/target/*/xml/*.xml', fingerprint: true
        }
        cleanup {
            cleanWs()
        }
    }
}
