def utils
pipeline {
    agent any
     stages {
        stage ("setup") {
            steps {
                script {
                    // load utility function
                    def rootDir = pwd()
                    utils = load "${rootDir}/jenkins/groovy/Utils.groovy"
                    // checkout repos
                    utils.SetupRepos(env.VIDEO_INFRA_BRANCH)
                }
            }
        }  
        stage ("extract torture test github credentials") {
            steps {
                script {
                    dir("infra-configuration") {
                        withCredentials([
                            string(credentialsId: 'ansible-vault-password', variable: 'ANSIBLE_VAULT_PASSWORD_PATH')
                        ]) {
                            utils.SetupAnsible()
                            sh(
                                script: """#!/bin/bash
                                ENCRYPTED_CREDENTIALS_FILE=ansible/secrets/torture.yml
                                export TORTURE_GITHUB_USER=$(ansible-vault view $ENCRYPTED_CREDENTIALS_FILE --vault-password $VAULT_PASSWORD_FILE | yq eval ".torture_github_user" -)
                                export TORTURE_GITHUB_TOKEN=$(ansible-vault view $ENCRYPTED_CREDENTIALS_FILE --vault-password $VAULT_PASSWORD_FILE | yq eval ".torture_github_token" -)"""
                            )
                        }
                    }
                }
            }

        }
        stage ("run longlived conference test") {
            steps {
                script {
                    dir("infra-provisioning") {
                        withCredentials([
                            string(credentialsId: 'jenkins-aws-secret', variable: 'AWS_SECRET_ACCESS_KEY'),
                            string(credentialsId: 'jenkins-aws-id', variable: 'AWS_ACCESS_KEY_ID')
                        ]) {
                            sh(
                                script: "scripts/synthetic-longlived-test.sh"
                            )
                        }
                    }
                }
            }
        }
     }
     post {
        always {
            cleanWs()
        }
    }
}
