def utils

pipeline {
    agent any
    options {
        timestamps()
        ansiColor('xterm')
    }
    stages {
        // output stage, shows off our input parameters
        stage ("setup") {
            steps {
                script {
                    // load utility function
                    def rootDir = pwd()
                    utils = load "${rootDir}/jenkins/groovy/Utils.groovy"
                    // checkout repos
                    utils.SetupRepos(env.VIDEO_INFRA_BRANCH)

                    // setup OCI credentials
                    utils.SetupOCI()
                }
            }
        }
        stage ("destroy coturn") {
            steps {
                script {
                    echo 'haproxy destruction beginning'
                    dir('infra-provisioning') {
                        withCredentials([
                            string(credentialsId: 'oci-jenkins-terraform-aws-secret', variable: 'AWS_SECRET_ACCESS_KEY'),
                            string(credentialsId: 'oci-jenkins-terraform-aws-id', variable: 'AWS_ACCESS_KEY_ID')
                        ]) {
                          sshagent(credentials: ['ssh-ubuntu']) {
                            sh '''#!/bin/bash
                            terraform/destroy-coturn-stack/destroy-coturn-stack-oracle.sh ubuntu'''
                          }
                        }
                    }
                }
            }
        }
    }
}
