def utils
pipeline {
  agent any
  options {
    timestamps()
    ansiColor('xterm')
    buildDiscarder(logRotator(numToKeepStr: '50', artifactNumToKeepStr: '50'))
  }
  stages {
    stage('Prepare/Checkout') { // for display purposes
      steps {
        script {
          // load utility function
          def rootDir = pwd()
          utils = load "${rootDir}/jenkins/groovy/Utils.groovy"
          // checkout repos
          utils.SetupRepos(env.VIDEO_INFRA_BRANCH)

          // setup OCI credentials
          utils.SetupOCI()

          sh 'rm -rf test-results'
          sh 'mkdir test-results'
        }
      }
    }
    stage('Provision') {
      steps {
        script {
          sshagent (credentials: ['ssh-ubuntu']) {
            dir('infra-configuration') {
              sh 'scripts/configure-jitsi-repo.sh'
            }
            def grid = env.GRID_URL
            if ((grid == '') || (grid == null)) {
              grid = 'validate'
            }
            lock("validate-grid-${grid}") {
              dir('infra-provisioning') {
                withCredentials([
                    string(credentialsId: 'asap-client-jwt-kid-meet', variable: 'ASAP_CLIENT_JWT_KID_MEET'),
                    string(credentialsId: 'asap-client-jwt-kid-beta', variable: 'ASAP_CLIENT_JWT_KID_BETA'),
                    string(credentialsId: 'asap-client-jwt-kid-prod', variable: 'ASAP_CLIENT_JWT_KID_PROD'),
                    string(credentialsId: 'asap-client-jwt-kid-stage', variable: 'ASAP_CLIENT_JWT_KID_STAGE'),
                    file(credentialsId: 'asap-client-jwt-key-meet', variable: 'ASAP_CLIENT_JWT_KEY_MEET'),
                    file(credentialsId: 'asap-client-jwt-key-prod', variable: 'ASAP_CLIENT_JWT_KEY_PROD'),
                    file(credentialsId: 'asap-client-jwt-key-stage', variable: 'ASAP_CLIENT_JWT_KEY_STAGE'),
                    file(credentialsId: 'asap-client-jwt-key-beta', variable: 'ASAP_CLIENT_JWT_KEY_BETA')
                ]) {
                  sh """#!/bin/bash
                  export ANSIBLE_FORCE_COLOR=True
                  scripts/validate-shards.sh ${env.ENVIRONMENT} \"${env.SHARDS}\" ubuntu"""
                }
              }
            }
          }
        }
      }
    }
  }
  post {
    always {
        dir('test-results') {
            sh '''#!/bin/bash
                for i in *; do 
                cd \$i;
                for z in *.zip; do
                    unzip \$z
                done
                cd -
                done'''     
        }
        archiveArtifacts artifacts: 'test-results/**/*', fingerprint: true
        junit 'test-results/**/target/chrome-2-chrome/*.xml'
        archiveArtifacts artifacts: 'test-results-*/**', fingerprint: true
    }
    fixed {
        slackSend color: "good", message: "Successfully fixed build of ${env.JOB_NAME} ${env.BUILD_NUMBER} (<${env.BUILD_URL}|Open>)\nValidating shards in $ENVIRONMENT -> $SHARDS"
    }
    failure {
        slackSend color: "danger", message: "Failure in build of build of ${env.JOB_NAME} ${env.BUILD_NUMBER} (<${env.BUILD_URL}|Open>)\nValidating shards in $ENVIRONMENT -> $SHARDS"
    }
    cleanup {
        cleanWs()
    }
  }
}
