def utils
pipeline {
    agent any
    options {
        timestamps()
        ansiColor('xterm')
        buildDiscarder(logRotator(numToKeepStr: '10', artifactNumToKeepStr: '10'))
    }
    stages {
        // output stage, shows off our input parameters
        stage ("setup") {
            steps {
                script {
                    // load utility function
                    def rootDir = pwd()
                    utils = load "${rootDir}/jenkins/groovy/Utils.groovy"
                    // checkout repos
                    utils.SetupRepos(env.VIDEO_INFRA_BRANCH)

                    // setup OCI credentials
                    utils.SetupOCI()
                }
            }
        }
        stage ("download repo processing") {
            steps {
                script {
                    echo 'download repo rebuild'
                    dir('infra-provisioning') {
                      lock("download-repo") {
                        withCredentials([
                            file(credentialsId: 'ops-repo-s3fs', variable: 'S3_PASSWORD_PATH'),
                            file(credentialsId: 'ops-repo-secring', variable: 'OPS_REPO_SECRING_PATH'),
                            file(credentialsId: 'ops-repo-pubring', variable: 'OPS_REPO_PUBRING_PATH'),
                            file(credentialsId: 'ops-repo-secring-passphrase', variable: 'OPS_REPO_SECRING_PASSPHRASE_PATH')
                        ]) {
                          sshagent(credentials: ['ssh-jenkins-ci']) {
                            sh '''#!/bin/bash
                                set -x
                                sudo cp $S3_PASSWORD_PATH /etc/.passwd-s3fs
                                sudo chown 600 /etc/.passwd-s3fs
                                mkdir -p /home/jenkins/jitsi/gnupg-jitsi
                                chmod 0700 /home/jenkins/jitsi/gnupg-jitsi
                                cp $OPS_REPO_SECRING_PATH /home/jenkins/jitsi/gnupg-jitsi/secring.gpg
                                cp $OPS_REPO_PUBRING_PATH /home/jenkins/jitsi/gnupg-jitsi/pubring.gpg
                                cp $OPS_REPO_SECRING_PASSPHRASE_PATH /home/jenkins/jitsi/gnupg-jitsi/passphrase
                                export ENVIRONMENT="torture-test" 
                                export OPS_REPO_BUCKET="download-repo"
                                export OPS_REPO_MOUNT_PATH="/mnt/download-repo"
                                export REPO_PATH="/mnt/download-repo/repo"
                                mkdir -p /mnt/download-repo
                                scripts/update-ops-repo.sh
                                exit $?'''
                          }
                        }
                      }
                    }
                }
            }
        }
    }
}
