def utils

pipeline {
    agent any
    options {
        ansiColor('xterm')
        timestamps()
        buildDiscarder(logRotator(numToKeepStr: '10', artifactNumToKeepStr: '10'))
    }
    stages {
        // output stage, shows off our input parameters
        stage ("setup") {
            steps {
                script {
                    // load utility function
                    def rootDir = pwd()
                    utils = load "${rootDir}/jenkins/groovy/Utils.groovy"
                    // checkout repos
                    utils.SetupRepos(env.VIDEO_INFRA_BRANCH)

                    // setup OCI credentials
                    utils.SetupOCI()
                    dir('infra-provisioning/scripts/aggregate-release-stats') {
                        sh 'mkdir -p pre-terminate-stats'
                    }
                }
            }
        }
        stage ("stats aggregation") {
            steps {
                script {
                    echo 'stats aggregation beginning'
                    dir('infra-provisioning/scripts/aggregate-release-stats') {
                        sh 'aggregate-release-stats.sh'
                    }
                }
            }
        }
    }
    post {
        always {
            archiveArtifacts artifacts: 'infra-provisioning/scripts/aggregate-release-stats/pre-terminate-stats/**'
            // Clean up afterwards
            cleanWs()
        }
    }
}
