node {   
    agent any
    stage('Prepare/Checkout') { // for display purposes
        dir('infra-configuration') {
            git branch: env.VIDEO_INFRA_BRANCH, url: env.INFRA_CONFIGURATION_REPO, credentialsId: 'jenkins-infra'
        }
        dir('infra-customization') {
            git branch: env.VIDEO_INFRA_BRANCH, url: env.INFRA_CUSTOMIZATION_REPO, credentialsId: 'jenkins-infra'
        }
        sh 'cp -a infra-customization/* infra-configuration'
        sh 'cp -a infra-customization/* infra-provisioning'
    }

    stage('Provision') {
       dir('infra-provisioning') {
        if (env.CLOUD_PROVIDER == 'oracle') {
                sh 'terraform/standalone/create-standalone-server-oracle.sh'
            } else {
                sh 'scripts/create-app-standalone-stack.sh'
            }
       }
    // Run the cloud provisioning
    }

    stage('Configure') {
        dir('infra-configuration') {
            sh 'scripts/configure-standalone.sh'
        }
    }
}