def provisionJob(job_name,environment,oracle_region,video_infra_branch) {
    def provision = build job: job_name, parameters: [
        [$class: 'StringParameterValue', name: 'ENVIRONMENT', value: environment],
        [$class: 'StringParameterValue', name: 'ORACLE_REGION', value: oracle_region],
        [$class: 'StringParameterValue', name: 'VIDEO_INFRA_BRANCH', value: video_infra_branch]
    ]

    return provision
}
// global var to track git branch from env or new tags
def utils

pipeline {				//indicate the job is written in Declarative Pipeline
    agent any				//agent specifies where the pipeline will execute.
    options {
      ansiColor('xterm')
      timestamps()
      buildDiscarder(logRotator(numToKeepStr: '10', artifactNumToKeepStr: '10'))
    }
    stages {
        // output stage, shows off our input parameters
        stage('Prepare/Checkout') {
            steps {
                script {
                    echo 'Observability stack release'
                    // load utility function
                    def rootDir = pwd()
                    utils = load "${rootDir}/jenkins/groovy/Utils.groovy"
                    // checkout repos
                    utils.SetupRepos(env.VIDEO_INFRA_BRANCH)

                    // setup OCI credentials
                    utils.SetupOCI()
                }
            }
        }

        stage("provision observability regions") {
            steps {
                script {
                  dir('infra-provisioning') {
                    echo "Provision observability stack in environment ${env.ENVIRONMENT}, clouds ${env.CLOUDS}";
                    def region_list = utils.SplitNomadRegions(env.ENVIRONMENT,env.REGIONS);
                    echo "region list ${region_list}";
                    def branches = [:]
                    for(i = 0; i < region_list.size(); i++) {
                        def oracle_region = region_list[i]
                        echo "pipeline branch ${curr} for ${cloud_list[curr]} ${oracle_region}";
                        branches["Build vector-${oracle_region}"] = {
                            provisionJob('provision-nomad-vector',
                                env.ENVIRONMENT,
                                oracle_region,
                                env.VIDEO_INFRA_BRANCH
                            )
                        }
                        branches["Build loki-${cloud_list[curr]}"] = {
                            provisionJob('provision-nomad-loki',
                                env.ENVIRONMENT,
                                oracle_region,
                                env.VIDEO_INFRA_BRANCH
                            )
                        }
                        branches["Build prometheus-${cloud_list[curr]}"] = {
                            provisionJob('provision-nomad-prometheus',
                                env.ENVIRONMENT,
                                oracle_region,
                                env.VIDEO_INFRA_BRANCH
                            )
                        }
                        branches["Build alertmanager-${cloud_list[curr]}"] = {
                            provisionJob('provision-nomad-alertmanager',
                                env.ENVIRONMENT,
                                oracle_region,
                                env.VIDEO_INFRA_BRANCH
                            )
                        }
                        branches["Build telegraf-${cloud_list[curr]}"] = {
                            provisionJob('provision-nomad-telegraf',
                                env.ENVIRONMENT,
                                oracle_region,
                                env.VIDEO_INFRA_BRANCH
                            )
                        }
                        branches["Build cloudprober-${cloud_list[curr]}"] = {
                            provisionJob('provision-nomad-cloudprober',
                                env.ENVIRONMENT,
                                oracle_region,
                                env.VIDEO_INFRA_BRANCH
                            )
                        }
                    }
                    // branch out here, run all jobs at once
                    // only succeed if all branches succeed
                    parallel branches
                  }
                }
            }
        }
    }
}