def utils

def oracle_regions(cloud_list) {
    def oracle_regions=[]
    for(i = 0; i < cloud_list.size(); i++) {
        oracle_regions[i] = utils.OracleRegionFromCloud(cloud_list[i])
    }
    return oracle_regions
}

def coturnClouds(clouds) {
    def coturn_clouds
    if (!clouds) {
        coturn_clouds = sh(
            returnStdout: true,
            script: '''#!/bin/bash
                source clouds/all.sh
                echo $COTURN_CLOUDS'''
        ).trim().split(' ')
    } else {
        coturn_clouds = clouds.split(' ')
    }
    return coturn_clouds
}


// global var to track git branch from env or new tags
def git_branch

// trigger create or update stack job with appropriate parameters
def createCoturnStack(stack_environment,cloud_provider,cloud_name,oracle_region,coturn_release_number,gitBranch) {
    def createStack = build job: 'provision-coturn',parameters: [
        [$class: 'StringParameterValue', name: 'ENVIRONMENT', value: stack_environment],
        [$class: 'StringParameterValue', name: 'CLOUD_NAME', value: cloud_name],
        [$class: 'StringParameterValue', name: 'ORACLE_REGION', value: oracle_region],
        [$class: 'StringParameterValue', name: 'CLOUD_PROVIDER', value: cloud_provider],
        [$class: 'StringParameterValue', name: 'COTURN_RELEASE_NUMBER', value: coturn_release_number],
        [$class: 'StringParameterValue', name: 'RELEASE_BRANCH', value: gitBranch],
        [$class: 'StringParameterValue', name: 'VIDEO_INFRA_BRANCH', value: env.VIDEO_INFRA_BRANCH]
    ]

    return createStack
}

pipeline {				//indicate the job is written in Declarative Pipeline
    agent any				//agent specifies where the pipeline will execute. 
    options {
        ansiColor('xterm')
        timestamps()
        buildDiscarder(logRotator(numToKeepStr: '10', artifactNumToKeepStr: '10'))
    }
    stages {
        stage('Prepare/Checkout') { // for display purposes
            steps {
                script {
                    // load utility function
                    def rootDir = pwd()
                    utils = load "${rootDir}/jenkins/groovy/Utils.groovy"
                    // checkout repos
                    utils.SetupRepos(env.VIDEO_INFRA_BRANCH)

                    // setup OCI credentials
                    utils.SetupOCI()
                }
            }
        }
        // output stage, shows off our input parameters
        stage ("setup") {
            steps {
                echo 'HAProxy Release Creation'
            }
        }
        // tag the new release or load git_branch from input parameters
        stage("tag release") {
          steps {
            script {
                // use incoming branch/tag or tag repo with new tag based on build ID
                // either way set it into git_branch variable to use later
                git_branch = utils.TagRelease('coturn-release',env.BUILD_ID, env.RELEASE_BRANCH)
                env.RELEASE_BRANCH = git_branch
            }
          }
        }
        // create or update stacks for the release
        stage("create stacks") {
            steps {
                script {
                    dir('infra-provisioning') {
                        echo "Create stacks in ${env.ENVIRONMENT} clouds ${env.CLOUDS}";
                        def cloud_list = coturnClouds(env.CLOUDS);
                        def oracle_region = oracle_regions(cloud_list);
                        echo "cloud list ${cloud_list}";
                        def branches = [:]
                        for(i = 0; i < cloud_list.size(); i++) {
                            def curr = i
                            echo "pipeline branch ${curr} for stack in ${cloud_list[curr]}";
                            branches["Build ${cloud_list[curr]}"] = {
                                createCoturnStack(env.ENVIRONMENT,
                                    env.CLOUD_PROVIDER,
                                    cloud_list[curr],
                                    oracle_region[curr],
                                    env.BUILD_ID,
                                    git_branch
                                )
                            }
                        }
                        // branch out here, run all create jobs at once
                        // only succeed if all branches succeed
                        parallel branches
                    }
                }
            }
        }
    }
}