def provisionJob(shard_environment,oracle_region,video_infra_branch) {
    def provision = build job: 'provision-nomad-telegraf',parameters: [
        [$class: 'StringParameterValue', name: 'ENVIRONMENT', value: shard_environment],
        [$class: 'StringParameterValue', name: 'ORACLE_REGION', value: oracle_region],
        [$class: 'StringParameterValue', name: 'VIDEO_INFRA_BRANCH', value: video_infra_branch]
    ]

    return provision
}

def utils
def governance
def artConfig

pipeline {
    agent any
    options {
      ansiColor('xterm')
      timestamps()
      buildDiscarder(logRotator(numToKeepStr: '10', artifactNumToKeepStr: '10'))
    }
    stages {
        stage('Prepare/Checkout') {
            steps {
                script {
                    echo 'telegraf release'
                    def rootDir = pwd()
                    utils = load "${rootDir}/jenkins/groovy/Utils.groovy"
                    utils.SetupRepos(env.VIDEO_INFRA_BRANCH)
                    utils.SetupOCI()

                    governance = utils.LoadGovernanceHooks()
                    artConfig = governance.init([
                        serviceName: 'nomad-telegraf',
                        version:     env.BUILD_ID,
                        environment: env.ENVIRONMENT,
                        fastTrack:   true,
                    ])
                }
            }
        }

        stage('Pre-Release') {
            steps {
                script {
                    governance.preRelease(artConfig)
                }
            }
        }

        stage('Pre-Deploy') {
            steps {
                script {
                    governance.preDeploy(artConfig)
                }
            }
        }

        stage("provision telegraf regions") {
            steps {
                script {
                  dir('infra-provisioning') {
                    echo "provision telegraf in environment ${env.ENVIRONMENT}, regions ${env.REGIONS}";
                    def region_list = utils.SplitNomadRegions(env.ENVIRONMENT,env.REGIONS);
                    echo "region list ${region_list}";
                    def branches = [:]
                    for(i = 0; i < region_list.size(); i++) {
                        def oracle_region = region_list[i]
                        echo "pipeline branch ${i} for ${oracle_region}";
                        branches["Build telegraf-${oracle_region}"] = {
                            provisionJob(env.ENVIRONMENT,
                                oracle_region,
                                env.VIDEO_INFRA_BRANCH
                            )
                        }
                    }
                    parallel branches
                  }
                }
            }
        }
    }

    post {
        always {
            script {
                governance.postHooks(artConfig, currentBuild.result == 'SUCCESS')
            }
        }
    }
}
