def createJigasiHAProxyStackOracle() {
    sh(
        script: """#!/bin/bash
        export USER_PUBLIC_KEY_PATH=~/.ssh/ssh_key.pub
        export ENVIRONMENT=${env.ENVIRONMENT}
        export ORACLE_REGION=${env.ORACLE_REGION}
        export ORACLE_GIT_BRANCH=${env.RELEASE_BRANCH}
        terraform/jigasi-proxy/create-jigasi-proxy-oracle.sh ubuntu"""
    )
}

def utils
pipeline {
    agent any
    options {
        ansiColor('xterm')
        timestamps()
        buildDiscarder(logRotator(numToKeepStr: '10', artifactNumToKeepStr: '10'))
    }
    stages {
        stage('Prepare/Checkout') { // for display purposes
            steps {
                script {
                    // load utility function
                    def rootDir = pwd()
                    utils = load "${rootDir}/jenkins/groovy/Utils.groovy"
                    // checkout repos
                    utils.SetupRepos(env.VIDEO_INFRA_BRANCH)

                    // setup OCI credentials
                    utils.SetupOCI()

                    sh 'mkdir -p test-results'
                }
            }
        }
        stage ("Jigasi HAProxy Stack Creation") {
            steps {
                script {
                    dir("infra-provisioning") {
                        withCredentials([
                            string(credentialsId: 'oci-jenkins-terraform-aws-secret', variable: 'AWS_SECRET_ACCESS_KEY'),
                            string(credentialsId: 'oci-jenkins-terraform-aws-id', variable: 'AWS_ACCESS_KEY_ID'),
                            sshUserPrivateKey(credentialsId: 'ssh-ubuntu', keyFileVariable: 'USER_PRIVATE_KEY_PATH',usernameVariable: 'SSH_USERNAME')
                        ]) {
                            utils.SetupSSH()
                            sshagent (credentials: ['ssh-ubuntu']) {
                                createJigasiHAProxyStackOracle()
                            }
                        }
                    }
                }
            }
        }
    }
    post {
        always {
            archiveArtifacts artifacts: 'test-results/**', allowEmptyArchive: true
            // Clean up afterwards
            cleanWs()
        }
    }
}
