#!/bin/bash

tpl /defaults/config.toml.tpl > /local/config.toml

export BROWSER_DISPLAY_NAME="Chrome"
export BROWSER_NAME="chrome"
if [ "$(dpkg --print-architecture)" = "amd64" ]; then
    export BROWSER_VERSION="$(google-chrome --version | awk '{print $3}')"
    export BROWSER_BINARY_CHROME="$(which google-chrome)"
else
    export BROWSER_VERSION="$(chromium --version | awk '{print $2}')"
    export BROWSER_BINARY_CHROME="$(which chromium)"
fi
tpl /defaults/driver_config.toml.tpl >> /local/config.toml

export BROWSER_DISPLAY_NAME="Firefox"
export BROWSER_NAME="firefox"
export BROWSER_VERSION="$(firefox --version | awk '{print $3}')"
export BROWSER_BINARY_FIREFOX="$(which firefox)"
tpl /defaults/driver_config.toml.tpl >> /local/config.toml
