def versioningManagerSetEarlyAccess(environment, release_number) {
    sh(
        script: """#!/bin/bash
export VERSIONING_ACTION=SET_RELEASE_EARLY_ACCESS
export VERSIONING_RELEASE="${release_number}"
ENVIRONMENT=${environment} scripts/versioning-manager.sh
"""
    )
}

pipeline {
    agent any
    options {
        ansiColor('xterm')
        timestamps()
        buildDiscarder(logRotator(numToKeepStr: '10', artifactNumToKeepStr: '10'))
    }
    stages {
        stage ("setup") {
            steps {
                script {
                    // load utility function
                    def rootDir = pwd()
                    utils = load "${rootDir}/jenkins/groovy/Utils.groovy"
                    // checkout repos
                    utils.SetupRepos(env.VIDEO_INFRA_BRANCH)

                    // setup OCI credentials
                    utils.SetupOCI()

                    sh 'mkdir -p test-results'
                }
            }
        }  
        stage ("load flags") {
            steps {
                script {
                    dir("infra-provisioning") {
                        useReleaseBackends = utils.GetEnvironmentVar(env.ENVIRONMENT, "USE_RELEASE_BACKENDS")
                        echo useReleaseBackends
                        recordReleases = utils.GetAnsibleVar(env.ENVIRONMENT, "release_recording_enabled")
                        echo recordReleases
                    }
                }
            }
        }
        stage ("set release EARLY_ACCESS in versioning manager") {
            when {
                expression { useReleaseBackends == 'true' }
            }
            steps {
                script {
                    dir("infra-provisioning") {
                        withCredentials([
                            string(credentialsId: 'asap-jwt-kid-dev', variable: 'ASAP_JWT_KID_DEV'),
                            string(credentialsId: 'asap-jwt-kid-prod', variable: 'ASAP_JWT_KID_PROD'),
                            file(credentialsId: 'asap-jwt-key-dev', variable: 'ASAP_JWT_KEY_DEV'),
                            file(credentialsId: 'asap-jwt-key-prod', variable: 'ASAP_JWT_KEY_PROD')
                        ]) {
                            versioningManagerSetEarlyAccess(env.ENVIRONMENT, env.RELEASE_NUMBER)
                        }
                    }
                }
            }
        }
        stage ("record release in docs-private") {
            when {
                expression { recordReleases == 'true' }
            }
            steps {
                script {
                    build job: 'record-release',parameters: [
                            [$class: 'StringParameterValue', name: 'ENVIRONMENT', value: env.ENVIRONMENT],
                            [$class: 'StringParameterValue', name: 'RELEASE_ID', value: env.BUILD_ID],
                            [$class: 'StringParameterValue', name: 'RELEASE_TYPE', value: 'core'],
                            [$class: 'StringParameterValue', name: 'RELEASE_ACTION', value: 'earlyaccess'],
                            [$class: 'StringParameterValue', name: 'VIDEO_INFRA_BRANCH', value: env.VIDEO_INFRA_BRANCH]
                        ]
                }
            }        
        }
     }
     post {
        always {
            cleanWs()
        }
        failure {
            slackSend color: "danger", message: "${env.JOB_NAME} - build ${env.BUILD_NUMBER} failed to set release ${env.RELEASE_NUMBER} as EARLY_ACCESS in ${env.ENVIRONMENT}"
        }
    }
}
