def utils
pipeline {
  agent any
  options {
      ansiColor('xterm')
      timestamps()
      buildDiscarder(logRotator(numToKeepStr: '10', artifactNumToKeepStr: '10'))
  }
  stages {
    stage('Prepare/Checkout') { // for display purposes
      steps {
        script {
          // load utility function
          def rootDir = pwd()
          utils = load "${rootDir}/jenkins/groovy/Utils.groovy"
          // checkout repos
          utils.SetupRepos(env.VIDEO_INFRA_BRANCH)

          // setup OCI credentials
          utils.SetupOCI()

        }
      }
    }
    stage('Provision') {
      steps {
        dir('infra-provisioning') {
          script {
            // include vault password for bucket credentials
            utils.SetupAnsible()
            withCredentials([
                sshUserPrivateKey(credentialsId: 'video-infra', keyFileVariable: 'USER_PRIVATE_KEY_PATH', usernameVariable: 'SSH_USERNAME'),
            ]) {
                sh 'scripts/create-buckets-oracle.sh'
                sh 'scripts/create-bucket-credentials-oracle.sh'
            }
          }
        }
      }
    }
  }
}