pipeline {
    agent any
    options {
        ansiColor('xterm')
        timestamps()
        buildDiscarder(logRotator(numToKeepStr: '10', artifactNumToKeepStr: '10'))
    }
    stages {
        stage('Prepare/Checkout') {
            steps {
                script {
                    sh 'docker buildx create --name mybuilder --driver docker-container --bootstrap --use'
                }
            }
        }
        stage('Build and Push Docker Image') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'dockerhub', usernameVariable: 'DOCKER_USER', passwordVariable: 'DOCKER_PASS')]) {
                    dir('docker/ops-jenkins') {
                        sh '''#!/bin/bash
                        DOCKER_AUTH=$(echo -n "$DOCKER_USER:$DOCKER_PASS" | base64)
                        export DOCKER_CONFIG="$(pwd)/.docker-ops-jenkins"
                        mkdir -p "$DOCKER_CONFIG"
                        echo '{"auths":{"https://index.docker.io/v1/":{"auth":"'"$DOCKER_AUTH"'"}}}' > "$DOCKER_CONFIG/config.json"
                        [ -z "$TAG" ] && export TAG="$(git rev-parse --short HEAD)"
                        ./build.sh
                        '''
                    }
                }
            }
        }
    }
}
