def reloadHaproxy() {
    sh(
        script: """#!/bin/bash
        export LOG_DEST="../../test-results"
        export ANSIBLE_FORCE_COLOR=True
        scripts/reload-haproxy.sh ubuntu
        exit \$?"""
    )
}
def utils
pipeline {
    agent any
    options {
        timestamps()
        ansiColor('xterm')
    }
    stages {
        // output stage, shows off our input parameters
        stage ("setup") {
            steps {
                script {
                    // load utility function
                    def rootDir = pwd()
                    utils = load "${rootDir}/jenkins/groovy/Utils.groovy"
                    // checkout repos
                    utils.SetupRepos(env.VIDEO_INFRA_BRANCH)

                    // setup OCI credentials
                    utils.SetupOCI()
                    sh 'mkdir -p test-results'
                }
            }
        }
        stage ("haproxy reload") {
            steps {
                script {
                    echo 'haproxy reload'
                    dir('infra-provisioning') {
                      lock("haproxy-state-${env.ENVIRONMENT}") {
                        withCredentials([
                            string(credentialsId: 'jenkins-aws-secret', variable: 'AWS_SECRET_ACCESS_KEY'),
                            string(credentialsId: 'jenkins-aws-id', variable: 'AWS_ACCESS_KEY_ID')                            
                        ]) {
                          sshagent (credentials: ['ssh-ubuntu']) {
                            reloadHaproxy()
                          }
                        }
                      }
                    }
                }
            }
        }
    }
    post {
        always {
            archiveArtifacts artifacts: 'test-results/**.log'
            // Clean up afterwards
            cleanWs()
        }
    }
}
